# Generated by Django 6.0.2 on 2026-02-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsession',
            name='candidate_id',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='terminated',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='captured_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='violation',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='examsession',
            index=models.Index(fields=['candidate_id', 'terminated'], name='proctor_exa_candida_ef0f72_idx'),
        ),
        migrations.AddIndex(
            model_name='screenshot',
            index=models.Index(fields=['session', '-captured_at'], name='proctor_scr_session_99e7a5_idx'),
        ),
        migrations.AddIndex(
            model_name='violation',
            index=models.Index(fields=['session', 'timestamp'], name='proctor_vio_session_431667_idx'),
        ),
    ]
