# Generated by Django 5.2.11 on 2026-02-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctor', '0004_exam_testresult_session_question_exam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsession',
            name='candidate_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
